# Site settings
title: پی‌نوشت
email: mo.pooya@gmail.com
author: پویا
description: "درباره‌ی وب، تکنولوژی، ایده، استارت‌آپ‌ها و سایر مسائل مورد علاقه‌ام می‌نویسم."
baseurl: "/fa"
url: "http://py4.ir"
google_analytics: 	

# Build settings
markdown: kramdown
permalink: none
paginate: 3
